name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clean install dependencies
        run: |
          Remove-Item -Path package-lock.json -ErrorAction SilentlyContinue
          npm install
        working-directory: frontend

      - name: Build and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
        working-directory: frontend
